export const VOTE_YES = "YES";
export const VOTE_NO = "NO";
export const VOTE_ERROR = "ERROR";
export const QUERY_COST = 0.001; // Cost per query in SOL (verify if needed)
export const QUERY_COST_FIXED_DECIMALS = 3;
export const USER_FREE_CREDITS_DEFAULT = 10;
export const USER_PAID_CREDITS_DEFAULT = 0;
export const QUERIES_REQUESTED_DEFAULT = 4;
export const USER_CREDIT_CONVERSION_DEFAULT = 1;
export const QUERIES_COST_EACH_DEFAULT = 1;
export const ALLOWED_AMOUNT_QUERIES = 20;